In [7]:
import pandas as pd

df = pd.read_json('output/page1a_flat.json')
df

,data_jobView_header_ageInDays,data_jobView_header_employer_name,data_jobView_header_employer_size,data_jobView_header_expired,data_jobView_header_jobTitleText,data_jobView_header_locationName,data_jobView_header_normalizedJobTitle,data_jobView_job_description,data_jobView_job_discoverDate,data_jobView_job_jobTitleText,...,data_jobView_overview_type,data_jobView_overview_website,data_jobView_overview_yearFounded,data_jobView_overview___typename,data_jobView___typename,data_jobView_overview_ceo,data_jobView_overview_links,data_jobView_overview_primaryIndustry,data_jobView_overview_ratings,data_jobView_overview_overview
0,6,McMakler Gmbh,501 bis 1.000 Mitarbeiter,False,Data Engineer (all genders),Berlin,Data Engineer,<div>Company Description<p><br/>We at McMakler...,2021-06-04T03:48:25,Data Engineer (all genders),...,Privatunternehmen,www.mcmakler.de/karriere,2015.0,Employer,JobView,NaN,NaN,NaN,NaN,NaN
1,13,None,None,False,Materialplaner Data Science / Data Analysis (m...,Berlin,Datenwissenschaftler (M/W/D),<div><div><div><div><p>&quot;Reparieren statt ...,2021-05-27T09:26:32,Materialplaner Data Science / Data Analysis (m...,...,None,None,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
2,15,BCG Platinion,501 bis 1.000 Mitarbeiter,False,Principal Software Engineer (m/f/d),Berlin,Principal Software Engineer,"<p>We are BCG Platinion, a part of the Boston ...",2021-05-26T05:02:14,Principal Software Engineer (m/f/d),...,Tochtergesellschaft oder Gesch√§ftsbereich,www.bcgplatinion.com/cema,2000.0,Employer,JobView,NaN,NaN,NaN,NaN,NaN
3,21,Vimcar GmbH,51 bis 200 Mitarbeiter,False,CRM Manager (m/f/d),Berlin,CRM Consultant Manager,<div><div><div>As one of Berlin's fastest grow...,2021-05-20T02:08:28,CRM Manager (m/f/d),...,Privatunternehmen,www.vimcar.de,2014.0,Employer,JobView,NaN,NaN,NaN,NaN,NaN
4,19,X24Factory GmbH,1 bis 50 Mitarbeiter,False,Marketing Data Engineer (m/w/d),Berlin,Data Engineer,<div><div><h5><b>Ihre Aufgaben</b></h5><div><u...,2021-05-21T10:00:44,Marketing Data Engineer (m/w/d),...,Privatunternehmen,www.moebel24.de,2015.0,Employer,JobView,NaN,NaN,NaN,NaN,NaN
5,7,clicks digital GmbH,Unbekannt,False,Head of Analytics / Remote (m/w/d),Berlin,Analytics Consultant (M/W/D),<p>Da bist du ja &ndash; wir haben schon auf d...,2021-06-03T02:24:31,Head of Analytics / Remote (m/w/d),...,Privatunternehmen,www.clicks.digital,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
6,8,MaibornWolff GmbH,Unbekannt,False,IT Strategy Consultant (m/w/d) Digital Identity,Berlin,Strategieberater (M/W/D),<div></div><div><div><div><h4><b>Vielfalt</b><...,2021-06-01T05:58:17,IT Strategy Consultant (m/w/d) Digital Identity,...,Privatunternehmen,www.maibornwolff.de,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
7,29,E.ON AG,Mehr als 10.000 Mitarbeiter,True,"Data Quality, Modeling & Provision Specialist ...",Berlin,None,<div><p>E.ON Digital Technology GmbH | Permane...,2021-05-12T03:03:10,"Data Quality, Modeling & Provision Specialist ...",...,Aktiengesellschaft,www.eon.com,2000.0,Employer,JobView,NaN,NaN,NaN,NaN,NaN
8,2,Zalando,Mehr als 10.000 Mitarbeiter,False,Fullstack Engineer (Java/Scala),Berlin,Software Developer,<div><p>As a full-stack engineer in Zalando's ...,2021-06-07T12:54:26,Fullstack Engineer (Java/Scala),...,Aktiengesellschaft,jobs.zalando.com,2008.0,Employer,JobView,NaN,NaN,NaN,NaN,NaN
9,6,None,None,False,Data Engineer/ Architect (w/m/d),Berlin,Dateningenieur (M/W/D),<p>FitX gibt es seit Ende 2009. Seitdem sind w...,2021-06-03T22:40:35,Data Engineer/ Architect (w/m/d),...,None,None,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
10,6,Zalando,Mehr als 10.000 Mitarbeiter,False,Senior Python Backend Engineer - Competitive &...,Berlin,Senior Back End Engineer,<div><p>The Competitive &amp; Analytics Engine...,2021-06-03T14:45:31,Senior Python Backend Engineer - Competitive &...,...,Aktiengesellschaft,jobs.zalando.com,2008.0,Employer,JobView,NaN,NaN,NaN,NaN,NaN
11,6,None,None,False,Data Engineer/ Architect (w/m/d) - Bernau bei ...,Berlin,Dateningenieur (M/W/D),<p>FitX gibt es seit Ende 2009. Seitdem sind w...,2021-06-03T22:40:35,Data Engineer/ Architect (w/m/d) - Bernau bei ...,...,None,None,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
12,7,ONE LOGIC,1 bis 50 Mitarbeiter,False,Government Advisory Manager (m/w/d),Berlin,Advisory Manager (M/W/D),<div><div><h5><b>Diese Aufgaben erwarten Dich<...,2021-06-02T10:02:41,Government Advisory Manager (m/w/d),...,Privatunternehmen,www.onelogic.de,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
13,15,None,None,False,Senior Data Scientist (m/w/d),Berlin,Senior Data Scientist,<p><b>Speak our language!</b></p><p><b>We are ...,2021-05-25T09:52:02,Senior Data Scientist (m/w/d),...,None,None,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
14,8,None,None,False,Performance-Marketing-Manager (m/w/d),Berlin,Manager Performance Analyst (M/W/D),<p>T&ouml;chter &amp; S&ouml;hne ist ein E-Hea...,2021-06-01T09:06:03,Performance-Marketing-Manager (m/w/d),...,None,None,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
15,6,None,None,False,Data Engineer/ Architect (w/m/d) - Potsdam,Potsdam,Dateningenieur (M/W/D),<p>FitX gibt es seit Ende 2009. Seitdem sind w...,2021-06-03T22:40:24,Data Engineer/ Architect (w/m/d) - Potsdam,...,None,None,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
16,8,Rundfunk Berlin-Brandenburg,1.001 bis 5.000 Mitarbeiter,False,Data Analyst / in Power BI,Berlin,Datenanalyst (M/W/D),<div></div><div><div><div><h1><b>Data Analyst ...,2021-06-01T09:12:16,Data Analyst / in Power BI,...,Unbekannt,www.rbb-online.de,2003.0,Employer,JobView,NaN,NaN,NaN,NaN,NaN
17,16,None,None,False,Engineering Manager - Risk Management,Berlin,Risk Manager,<div><h2>ABOUT THE TEAM</h2><p>As the Engineer...,2021-05-24T13:24:15,Engineering Manager - Risk Management,...,None,None,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
18,1,Toll Collect GmbH,501 bis 1.000 Mitarbeiter,False,Geo Data Analyst *in (d/m/w),Berlin,Datenanalyst (M/W/D),"Als anspruchsvolles, modernes Dienstleistungsu...",2021-06-09T01:50:34,Geo Data Analyst *in (d/m/w),...,Privatunternehmen,www.toll-collect.de,2005.0,Employer,JobView,NaN,NaN,NaN,NaN,NaN
19,19,Scout24 AG,201 bis 500 Mitarbeiter,False,Machine Learning Engineer(d/w/m),Berlin,Machine Learning Engineer,<div><p>Scout24 is a listed tech company that ...,2021-05-21T10:02:44,Machine Learning Engineer(d/w/m),...,Aktiengesellschaft,www.scout24.com,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
20,26,eschbach GmbH,1 bis 50 Mitarbeiter,False,IT Projektmanager / Cloud Operations (m/w/d),Berlin,Cloud Engineer (M/W/D),<p>Werde Teil eines agilen Experten-Teams und ...,2021-05-14T07:50:50,IT Projektmanager / Cloud Operations (m/w/d),...,Privatunternehmen,www.eschbach.com,2005.0,Employer,JobView,NaN,NaN,NaN,NaN,NaN
21,6,None,None,False,Data Engineer/ Architect (w/m/d) - K√∂nigs Wust...,K√∂nigs Wusterhausen,Dateningenieur (M/W/D),<p>FitX gibt es seit Ende 2009. Seitdem sind w...,2021-06-03T22:40:24,Data Engineer/ Architect (w/m/d) - K√∂nigs Wust...,...,None,None,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
22,7,Scout24 AG,201 bis 500 Mitarbeiter,False,Principal Data Scientist (f/m/d),Berlin,Principal Data Scientist,<div><p>Scout24 is a listed tech company that ...,2021-06-03T03:50:05,Principal Data Scientist (f/m/d),...,Aktiengesellschaft,www.scout24.com,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
23,6,None,None,False,Data Analyst - Unternehmensberatung (m/w/d),Berlin,Datenanalyst (M/W/D),<p>Wir haben ein Ziel. Wir wollen das f&uuml;h...,2021-06-03T15:24:13,Data Analyst - Unternehmensberatung (m/w/d),...,None,None,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
24,1,None,None,False,Business Intelligence Developer / Data Enginee...,Berlin,Dateningenieur (M/W/D),<p>Die Spiele-Palast GmbH entwickelt erfolgrei...,2021-06-09T02:48:50,Business Intelligence Developer / Data Enginee...,...,None,None,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
25,27,None,None,False,Senior Sales Manager,Berlin,Senior Sales Manager,<p>Responsibilities:</p><p>-Sell our products ...,2021-05-14T03:28:22,Senior Sales Manager,...,None,None,NaN,Employer,JobView,NaN,NaN,NaN,NaN,NaN
26,1,Movinga GmbH,51 bis 200 Mitarbeiter,False,Junior Data Scientist Marketing (m/f/d),Berlin,Junior Data Scientist,<p>Movinga is Europe's leading full-service mo...,2021-06-09T01:43:19,Junior Data Scientist Marketing (m/f/d),...,Privatunternehmen,www.movinga.de,2015.0,Employer,JobView,NaN,NaN,NaN,NaN,NaN
27,7,dentalXrai GmbH,1 bis 50 Mitarbeiter,False,(Senior) Machine Learning Engineer (m/f/d) (Re...,Berlin,Senior Machine Learning Engineer,"<p>Over the last decade, the application of ar...",2021-06-03T04:23:10,(Senior) Machine Learning Engineer (m/f/d) (Re...,...,Privatunternehmen,www.dentalxr.ai,2020.0,Employer,JobView,NaN,NaN,NaN,NaN,NaN
28,23,Toll Collect GmbH,501 bis 1.000 Mitarbeiter,False,(Senior) Big Data Analyst *in (d/m/w),Berlin,Senior Datenanalyst (M/W/D),<div></div><div><div><div><p>Als anspruchsvoll...,2021-05-17T13:54:45,(Senior) Big Data Analyst *in (d/m/w),...,Privatunternehmen,www.toll-collect.de,2005.0,Employer,JobView,NaN,NaN,NaN,NaN,NaN
29,15,RepRisk AG,1 bis 50 Mitarbeiter,False,Data Support and Integration Specialist,Berlin,Support Specialist,<p><b>About You</b></p><p>Are you looking to c...,2021-05-25T13:42:24,Data Support and Integration Specialist,...,Privatunternehmen,www.reprisk.com,1998.0,Employer,JobView,NaN,NaN,NaN,NaN,NaN